common_packages:
  - zsh
  - git
  - htop
  - wget
  - curl
  - vim
  - tmux
  - tree
  - jq
  - fzf
  - kubectl

mac_packages:
  - visual-studio-code  
  - iterm2
  - rectangle
  - alfred
  - k9s


linux_packages:
  - build-essential
  