common_packages:
  - zsh
  - git
  - htop
  - wget
  - curl
  - vim
  - tmux
  - tree
  - jq
  - fzf

mac_packages:
  - visual-studio-code  
  - iterm2
  - rectangle
  - alfred
  - kubectl
  - k9s


linux_packages:
  - build-essential
  