common_packages:
  - git
  - htop
  - wget
  - vim
  - node
  - nvm
  - python3
  - uv
  - golang
  - rust
  - kubectl
  - k9s

mac_packages:
  - visual-studio-code  # Homebrew package name

linux_packages:
  - code                # apt/dnf package name (may require Microsoft repo)

windows_packages:
  - Microsoft.VisualStudioCode  # winget package name