- name: Install packages on macOS
  include_tasks: mac.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install packages on Linux
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ linux_packages + common_packages }}"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install or upgrade Golang
  include_tasks: languages/golang.yml
  when: ansible_facts['os_family'] == 'Darwin' or ansible_facts['os_family'] == 'Debian'

- name: Install or upgrade Node.js
  include_tasks: languages/nodejs.yml
  when: ansible_facts['os_family'] == 'Darwin' or ansible_facts['os_family'] == 'Debian'


# - name: Setup nvm environment on macOS
#   include_tasks: nvm.yml
#   when: ansible_facts['os_family'] == 'Darwin'

# - name: Setup oh-my-zsh, powerlevel10k, and fonts on macOS
#   include_tasks: ohmyzsh.yml
#   when: ansible_facts['os_family'] == 'Darwin'