- name: Install packages on macOS
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages + mac_packages }}"
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install packages on Linux
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ common_packages + linux_packages }}"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install packages on Windows (winget)
  community.windows.win_winget:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages + windows_packages }}"
  when: ansible_facts['os_family'] == 'Windows'