
- name: Ensure nvm init in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "{{ ansible_env.HOME }}/.brew/opt/nvm/nvm.sh" ] && \. "{{ ansible_env.HOME }}/.brew/opt/nvm/nvm.sh"
      [ -s "{{ ansible_env.HOME }}/.brew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "{{ ansible_env.HOME }}/.brew/opt/nvm/etc/bash_completion.d/nvm"
    insertafter: EOF
    create: yes
    state: present